# Generated by Django 4.1.2 on 2022-10-10 08:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgID', models.CharField(max_length=50)),
                ('sender_mail', models.CharField(max_length=50)),
                ('spf_record', models.BooleanField(default=True)),
                ('dkim_record', models.BooleanField(default=True)),
                ('DMARC_record', models.BooleanField(default=True)),
                ('sender_ip', models.CharField(max_length=20)),
                ('record_time', models.DateTimeField(default=datetime.datetime(2022, 10, 10, 14, 14, 22, 603140))),
                ('rcode', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
