# Generated by Django 4.1.2 on 2022-10-10 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appreport_label_alter_appreport_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreport',
            name='record_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 0, 54, 14, 375443)),
        ),
    ]
