# Generated by Django 4.1.2 on 2022-10-11 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_appreport_dmarc_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreport',
            name='record_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 10, 7, 246728)),
        ),
    ]
