# Generated by Django 4.1.2 on 2022-10-12 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appreport_record_time'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='rdmstr',
        #     name='email',
        #     field=models.TextField(default=None, max_length=3000),
        # ),
        # migrations.AlterField(
        #     model_name='appreport',
        #     name='record_time',
        #     field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 23, 30, 13, 154133)),
        # ),
    ]
