# Generated by Django 4.1.2 on 2022-10-12 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rdmstr_email_alter_appreport_record_time'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='appreport',
        #     name='record_time',
        #     field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 23, 31, 16, 75685)),
        # ),
        # migrations.AlterField(
        #     model_name='rdmstr',
        #     name='email',
        #     field=models.TextField(default='nothing', max_length=3000),
        # ),
    ]
