# Generated by Django 4.1.2 on 2022-10-12 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_appreport_record_time_alter_rdmstr_email'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='rdmstr',
        #     name='email',
        # ),
        # migrations.AlterField(
        #     model_name='appreport',
        #     name='record_time',
        #     field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 23, 32, 42, 814206)),
        # ),
    ]
